config/routes.rb
Rails.application.routes.draw do
  get 'welcome' => 'pages#welcome'

  get 'index' => 'pages#index'

  get 'about' => 'pages#about'

  get 'dance' => 'pages#dance'

  get 'contact' => 'pages#contact'

  get 'codex' => 'pages#codex', :as => 'greatscotts', :path => 'greatscotts'

  root 'pages#welcome'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end

  def index
  end

  def about
  end

  def dance
  end

  def contact
  end

  def codex
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title LiningStarz
    %link{:href => "http://fonts.googleapis.com/css?family=<link href='http://fonts.googleapis.com/css?family=Lobster|Alfa+Slab+One|Racing+Sans+One|Corben|Squada+One|Yeseva+One|Bigshot+One' rel='stylesheet' type='text/css'>", :rel => "stylesheet", :type => "text/css"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Home", welcome_path, class: "navbar-brand"
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li= link_to "Index", index_path
            %li= link_to "About", about_path
            %li= link_to "Dance", dance_path
            %li
              = link_to "Contact", { :data => { :target => "#contact_us_modal", :toggle => "modal"}} do
                Contact
            %li= link_to "Codex", greatscotts_path
    = yield


#contact_us_modal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} &times;
        %h4.modal-title What's up?
      .modal-body
        %p Share your thoughts telepathically, or by emailing the group mailbox.
        %p LiningStarz@gmail.com
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Rejoyce

app/views/pages/about.html.haml
%h1 Pages#about
%p Find me in app/views/pages/about.html.erb

app/views/pages/codex.html.haml
#great_scots_page

  .container-md
    .text-center.pad-4x
      %h1.great_scotts_font_1 Great Scotts
      
      %h3.great_scotts_font_1
        October 10, 2015
        &mdash;
        Villa Rica, GA

      .pad-top.great_scotts_font_3
        %a#great_scotts_button.btn.btn-lg.btn-primary.btn-block{:href => "#great_scotts_details"} JOIN THE FUN!

  .container
    .row
      .col-md-6
        %h2.text-center.pad-top.great_scotts_name.great_scotts_font_3
          Scott Blevins
          .great_scotts_image_wrapper.pad-top
            = image_tag "scott_blevins.jpg"
        .text-left.pad-top.great_scotts_font_3
          %p Scott Blevins is an internationally known, award-winning choreographer, judge, and dance instructor. 
        .text-center.pad-top
          %a.btn.btn-lg.btn-primary.btn-block{:href => "http://www.scottblevins.com", :target => :blank} CHECK HIM OUT
      .col-md-6
        %h2.text-center.pad-top.great_scotts_name.great_scotts_font_3
          Scott Schrank
          .great_scotts_image_wrapper.pad-top
            = image_tag "scott_schrank.jpg"

        .text-left.pad-top.great_scotts_font_3
          %p Scott Schrank is a competitive dancer, with top awards, for dancing, teaching, and choreography.
        .text-center.pad-top
          %a.btn.btn-lg.btn-primary.btn-block{:href => "http://www.scottschrank.com", :target => :blank} CHECK HIM OUT

  #great_scotts_details.container-md
    .text-center
      %h2.great_scotts_font_1
        Join us for an unforgetable day of fun and dancing!
    .row.pad-top  
      .col-md-6.great_scotts_detail_heading
        %b Who:
      .col-md-6
        Great Scott's Teaching / Entertaining
        %br
        Great Friends Learning / Having Fun
    .row.pad-top  
      .col-md-6.great_scotts_detail_heading
        %b What:
      .col-md-6
        Easy to Intermediate line dances
    .row.pad-top  
      .col-md-6.great_scotts_detail_heading
        %b When:
      .col-md-6
        %table
          %tr
            %th{colspan: "2"} 
              %u
                October 10, 2015
          %tr
            %td
              9:30 am
            %td.pad-x
              Doors Open
          %tr
            %td
              10:00 am
            %td.pad-x
              Work Shops
          %tr
            %td
              5:00 pm
            %td.pad-x
              Dinner
          %tr
            %td
              7:30 pm
            %td.pad-x
              Dance Party!
          %tr
            %td
              11:00 pm
            %td.pad-x
              Last Dance

    .row.pad-top
      .col-md-6.great_scotts_detail_heading
        %b Where:
      .col-md-6
        Villa Rica Civic Center
        %br
        1605 Highway 61 Villa Rica, GA 30180
        %br
        678-929-8326
    .row.pad-top  
      .col-md-6.great_scotts_detail_heading
        %b Why:
      .col-md-6
        Why not?
    .pad-top-4x.great_scotts_font_3
      %a#great_scotts_button.btn.btn-lg.btn-primary.btn-block{:download => "", :href => "great_scotts_registration_2015.xlsx"} REGISTER

  #great_scotts_showcase.container
    %h2.great_scotts_font_3 Showcase Your Group
    %p.great_scotts_link
      If your group would like to perform a team showcase dance during the workshop, please contact us at 
      %a{:href => "mailto:liningstarz@gmail.com?subject=Great Scotts"} liningstarz@gmail.com
      to get on the schedule.

  #great_scotts_footer
    .container-md
      .row
        .col-md-4.text-center.pad-y-4x
          U Can Dance
        .col-md-4.text-center.pad-y-4x.great_scotts_link
          %a{:href => "mailto:liningstarz@gmail.com?subject=Great Scotts"} Contact Us
        .col-md-4.text-center.pad-y-4x
          &copy;
          2015

app/views/pages/contact.html.haml
%h1 Pages#contact
%p Find me in app/views/pages/contact.html.erb
%b LiningStarz@gmail.com

app/views/pages/dance.html.haml
#dance
  .container.pad
    %h1.text-center Let's Dance
    %p.text-center East Side Station every Wednesday: &nbsp 7(ish) until.
    .pad
      %h2 East Side Station is the place to party!
      %p http://www.eastsidestation.com/
      %p Full Bar. Full Kitchen. Full dance floor.
    .pad
      %h2 Heretic
      %p Inside the City
      %p http://www.hereticatlanta.com/thursday.html
      %p Straights Welcome

app/views/pages/index.html.haml
%h1 Pages#index
%p Find me in app/views/pages/index.html.erb

app/views/pages/welcome.html.haml
#welcome_header
  .container
    %h1.text-center.pad The Lining Starz
    %p.text-center.pad We dance.

#welcome_page_featured_image

#featured_sections
  .container
    .row
      .col-md-4.text-center.pad
        .featured_sections_columns
          %h2 Section 1
          %p The First Section
          .featured_sections_image
            picture goes here
      .col-md-4.text-center.pad
        .featured_sections_columns
          %h2 Section 2
          %p The Second Section
          .featured_sections_image
            picture goes here
      .col-md-4.text-center.pad
        .featured_sections_columns
          %h2 Section 3
          %p The Third Section
          .featured_sections_image
            picture goes here

#welcome_footer
  %p.pad We love to party